default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.14

  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: true
    max_acceleration: 4.0

  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: true
    max_acceleration: 4.0

  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.14

  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.14

  wrist_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.14